"""
Resilience Report — JSON schema + Markdown PR artifact.

The report is tamper-evident: integrity_hash is SHA-256 over the
lexicographically sorted JSON-serialized attack array.
"""

from __future__ import annotations

import hashlib
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path

from ..agents.breaker import Attack
from ..core.combat_pair import CombatResult

CONTROL_MAPPINGS = {
    "NIST_SSDF": ["RV.2.2", "RV.3.1", "PW.8.1"],
    "OWASP_SAMM": ["Verification/Security-Testing/2"],
    "SOC2_CC": ["CC7.1", "CC8.1"],
    "ISO_27001": ["A.14.2.8", "A.14.2.9"],
}


def generate_run_id() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%SZ")
    suffix = uuid.uuid4().hex[:4]
    return f"crucible-{ts}-{suffix}"


def build_report(
    result: CombatResult,
    run_id: str,
    spec_ref: str = "",
    commit_sha: str = "",
    playbook_version: str = "owasp_top10@v2025.1",
) -> dict:
    """Build the structured Resilience Report as a Python dict (serializable to JSON)."""
    attacks_serialized = [
        {
            "id": a.id,
            "cwe": a.cwe,
            "title": a.title,
            "description": a.description,
            "line_hint": a.line_hint,
            "confidence": a.confidence,
            "severity": a.severity,
            "score": a.score,
            "verdict": _score_to_verdict(a.score),
        }
        for a in result.all_attacks
    ]

    integrity_hash = _compute_hash(attacks_serialized)

    return {
        "schema_version": "1.0",
        "run_id": run_id,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "spec_ref": spec_ref,
        "commit_sha": commit_sha,
        "ars_score": result.final_ars,
        "attack_count": result.attack_count,
        "mitigated_count": result.mitigated_count,
        "partial_count": result.partial_count,
        "miss_count": result.miss_count,
        "rounds_completed": len(result.rounds),
        "early_exit": result.early_exit,
        "elapsed_seconds": round(result.total_elapsed_seconds, 2),
        "playbook_version": playbook_version,
        "attacks": attacks_serialized,
        "control_mappings": CONTROL_MAPPINGS,
        "integrity_hash": integrity_hash,
    }


def save_report(report: dict, reports_dir: Path) -> Path:
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / f"{report['run_id']}.json"
    with open(path, "w") as f:
        json.dump(report, f, indent=2)
    return path


def load_report(run_id: str, reports_dir: Path) -> dict:
    path = reports_dir / f"{run_id}.json"
    if not path.exists():
        raise FileNotFoundError(f"Report not found: {path}")
    with open(path) as f:
        return json.load(f)


def verify_integrity(report: dict) -> bool:
    """Re-derive hash and compare. Returns True if report is authentic."""
    stored = report.get("integrity_hash", "")
    derived = _compute_hash(report.get("attacks", []))
    return stored == derived


def render_markdown(report: dict) -> str:
    ars = report["ars_score"]
    gate = "✅ PASSED" if ars >= 0.80 else "❌ FAILED"
    verdict_icon = {
        "MITIGATED": "✅", "PARTIAL": "⚠️", "MISSED": "❌"
    }

    lines = [
        f"## 🛡️ CRUCIBLE Resilience Report",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Run ID | `{report['run_id']}` |",
        f"| ARS Score | **{ars:.2f}** |",
        f"| Gate | {gate} |",
        f"| Attacks | {report['attack_count']} fired · {report['mitigated_count']} mitigated · {report['miss_count']} missed |",
        f"| Rounds | {report['rounds_completed']} |",
        f"| Elapsed | {report['elapsed_seconds']}s |",
        f"| Playbook | `{report['playbook_version']}` |",
        f"",
        f"### Attack Breakdown",
        f"",
        f"| ID | CWE | Title | Severity | Verdict |",
        f"|----|-----|-------|----------|---------|",
    ]

    for a in report.get("attacks", []):
        icon = verdict_icon.get(a["verdict"], "?")
        lines.append(
            f"| {a['id']} | `{a['cwe']}` | {a['title']} | {a['severity']} | {icon} {a['verdict']} |"
        )

    lines += [
        f"",
        f"### Compliance Control Mappings",
        f"",
        f"| Framework | Controls |",
        f"|-----------|---------|",
    ]
    for framework, controls in report.get("control_mappings", {}).items():
        lines.append(f"| {framework} | {', '.join(controls)} |")

    lines += [
        f"",
        f"---",
        f"*Integrity: `{report['integrity_hash']}`*",
        f"*Generated by [CRUCIBLE](https://github.com/sanjoy1234/crucible)*",
    ]

    return "\n".join(lines)


def _score_to_verdict(score: float) -> str:
    if score >= 1.0:
        return "MITIGATED"
    if score >= 0.5:
        return "PARTIAL"
    return "MISSED"


def _compute_hash(attacks: list[dict]) -> str:
    canonical = json.dumps(attacks, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(canonical.encode()).hexdigest()
